on:
  push:
    branches:
      - main
    paths:
      - '20**/**'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      SESSION_ID: ${{ secrets.SESSION_ID }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Startup Selenium Docker
        uses: docker://selenium/standalone-chrome:latest
        with:
          args: --rm --name selenium -p 4444:4444

      - name: Download Images
        run: |
          python3 -m pip install -r requirements.txt
          python3 update-readme.py

      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Year Image"
          git push