on:
  push:
    branches:
      - main
    paths:
      - '20**/**'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      SESSION_ID: ${{ secrets.SESSION_ID }}

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4444:4444

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Images
        run: |
          pip install -U urllib3 requests
          python3 -m pip install -r requirements.txt
          python3 update-readme.py

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify'
          commit_user_name: GitHub Actions
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <github-actions[bot]@users.noreply.github.com>
          file_pattern: "assets/"
