on:
  push:
    branches:
      - main
    paths:
      - '20**/**'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      SESSION_ID: ${{ secrets.SESSION_ID }}

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4444:4444

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Images
        run: |
          pip install -U urllib3 requests
          python3 -m pip install -r requirements.txt
          python3 update-readme.py

      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Year Image"
          git push
